---
environment_name: local
hostname: oauth-fde-{{ environment_name }}
front_web_public_host: oauth-fde.test
is_development_environment: yes

hydra_system_secret: dTAiCVwMxP9VCizDhgC9iTq9NgbltuGf
hydra_cookie_secret: w1JFEbCBiOUigeEgZ4xo37Rnqm8m6amz
hydra_host: ""
hydra_port: 4444
hydra_root_client_id: "root"
hydra_root_client_secret: "root"
hydra_root_client_callback: "http://{{ front_web_public_host }}:3000"

postgresql_users:
  - name: root
    pass: root
    encrypted: no

app_env:
  HYDRA_CLIENT_ID: "{{ hydra_root_client_id }}"
  HYDRA_CLIENT_SECRET: "{{ hydra_root_client_secret }}"
  HYDRA_URL: "http://localhost:{{ hydra_port }}"
  COOKIE_SECRET: c0ec576616d244fc2cafcf1a961d20a0b19dad5992071c7f70023d64f0dffc2cf06520f7ad00fa68c55fd3c732fdad530eacff6353360671027d07d1bf466c54

app_users:
  - firstname: "Admin"
    lastname: "#MAVOIX"
    email: "admin@mavoix.info"
    password: "admin"
    is_admin: yes
  - firstname: "Test"
    lastname: "User"
    email: "test@test.com"
    password: "test"
    is_admin: no

pm2_apps:
    - name: keystonejs
      script: /vagrant/app/dist/index.js
      cwd: /vagrant/app
      instances: 1
      exec_mode: cluster
      restart_delay: 5000
      # env: written in the app/.env file
    - name: hydra
      script: hydra
      watch: yes
      args: "host --dangerous-force-http"
      env:
        HOST: "{{ hydra_host }}"
        PORT: "{{ hydra_port }}"
        COOKIE_SECRET: "{{ hydra_cookie_secret }}"
        DATABASE_URL: "{{ hydra_database_url }}"
        SYSTEM_SECRET: "{{ hydra_system_secret }}"
        FORCE_ROOT_CLIENT_CREDENTIALS: "{{ hydra_root_client_credentials }}"
        CONSENT_URL: "{{ hydra_root_client_callback }}/consent"
